[package]
name = "bonbon"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = { git = "https://github.com/lwus/bs58-rs" }
mpl-token-metadata = "1.2.5"
solana-sdk = "=1.10.9"
solana-transaction-status = "=1.10.9"
spl-token = "3.2.0"
