[package]
name = "bonbon"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
bs58 = "0.4.0"
mpl-token-metadata = "=1.3.3"
solana-account-decoder = { git = "https://github.com/omertxyz/solana.git", rev = "d791785f1feead3a858f636be8a865ab2611c2af" }
solana-sdk = { git = "https://github.com/omertxyz/solana.git", rev = "d791785f1feead3a858f636be8a865ab2611c2af" }
solana-transaction-status = { git = "https://github.com/omertxyz/solana.git", rev = "d791785f1feead3a858f636be8a865ab2611c2af" }
spl-token-2022 = "0.4.1"
spl-token = "3.3.0"
