[package]
name = "bonbon"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
bs58 = "0.4.0"
mpl-token-metadata = "1.3.3"
solana-account-decoder = { git = "https://github.com/omertxyz/solana.git", rev = "a9f03247d77f452b1461a7d3573f03216360b89f" }
solana-sdk = { git = "https://github.com/omertxyz/solana.git", rev = "a9f03247d77f452b1461a7d3573f03216360b89f" }
solana-transaction-status = { git = "https://github.com/omertxyz/solana.git", rev = "a9f03247d77f452b1461a7d3573f03216360b89f" }
spl-token = "3.3.0"
spl-token-2022 = "0.4.1"
