[package]
name = "bonbon"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
bs58 = "0.4.0"
mpl-token-metadata = "=1.3.3"
solana-account-decoder = { git = "https://github.com/omertxyz/solana.git", rev = "4f886c39d5e8fbfefc6363a8c69e04aafa51a783" }
solana-sdk = { git = "https://github.com/omertxyz/solana.git", rev = "4f886c39d5e8fbfefc6363a8c69e04aafa51a783" }
solana-transaction-status = { git = "https://github.com/omertxyz/solana.git", rev = "4f886c39d5e8fbfefc6363a8c69e04aafa51a783" }
spl-token = "=3.5.0"