[package]
name = "bonbon"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
bs58 = "0.4.0"
mpl-token-metadata = { git = "https://github.com/omertxyz/solana-nft-metadata.git", rev = "9f8de6a744f63f095f6cf79f8e8c5b558dca1ae1" }
solana-account-decoder = { git = "https://github.com/omertxyz/solana.git", rev = "0da726b10057897deea09e849097c6076c04443d" }
solana-sdk = { git = "https://github.com/omertxyz/solana.git", rev = "0da726b10057897deea09e849097c6076c04443d" }
solana-transaction-status = { git = "https://github.com/omertxyz/solana.git", rev = "0da726b10057897deea09e849097c6076c04443d" }
spl-token-2022 = "0.4.1"
spl-token = "3.3.0"
