[package]
name = "bonbon"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
bs58 = "0.4.0"
mpl-token-metadata = "=1.3.3"
solana-account-decoder = { git = "https://github.com/omertxyz/solana.git", rev = "6e9405eea3db6d0277679a12be0d7bd73560249f" }
solana-sdk = { git = "https://github.com/omertxyz/solana.git", rev = "6e9405eea3db6d0277679a12be0d7bd73560249f" }
solana-transaction-status = { git = "https://github.com/omertxyz/solana.git", rev = "6e9405eea3db6d0277679a12be0d7bd73560249f" }
spl-token = "=3.3.0"