[package]
name = "bonbon"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
bs58 = "0.4.0"
mpl-token-metadata = "=1.3.3"
solana-account-decoder = { git = "https://github.com/omertxyz/solana.git", rev = "87ae56b6386d220aaa8cb62e6feb26c1ab87c7b5" }
solana-sdk = { git = "https://github.com/omertxyz/solana.git", rev = "87ae56b6386d220aaa8cb62e6feb26c1ab87c7b5" }
solana-transaction-status = { git = "https://github.com/omertxyz/solana.git", rev = "87ae56b6386d220aaa8cb62e6feb26c1ab87c7b5" }
spl-token-2022 = "0.4.1"
spl-token = "3.3.0"
