[package]
name = "bonbon"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
bs58 = "0.4.0"
mpl-token-metadata = "=1.3.3"
solana-account-decoder = { git = "https://github.com/omertxyz/solana.git", rev = "c549f2550353d7ec1f6b8bbf242735f9e3896f17" }
solana-sdk = { git = "https://github.com/omertxyz/solana.git", rev = "c549f2550353d7ec1f6b8bbf242735f9e3896f17" }
solana-transaction-status = { git = "https://github.com/omertxyz/solana.git", rev = "c549f2550353d7ec1f6b8bbf242735f9e3896f17" }
spl-token-2022 = "0.4.1"
spl-token = "3.3.0"
